version: '3.9'

services:
  blog:
    tty: true
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - type: bind
        source: /home/bouningen/programs/Blog
        target: /blog
      - type: bind
        source: /home/bouningen/.ssh
        target: /root/.ssh
    command: [ "bash" ]
